package com.tur.services;

import com.tur.domain.Animal;

public interface AnimalService {

    Long create(Animal animal);                 //return autogenerated animalId

    Animal read(Long animalId);

    void update(Long animalId, Animal animal);

    void delete(Long animalId);
}
