package com.tur.services;

import com.tur.domain.Animal;

import java.util.List;
import java.util.Set;

public interface AnimalService {

    Long create(Animal animal);                 //return autogenerated animalId

    Animal read(Long animalId);

    void update(Long animalId, Animal animal);

    void delete(Long animalId);

    List<Animal> getAll();

    List<Animal> getAllSortedAlphabetically();

    List<Animal> getAllSortedReverseAlphabetically();

    List<Animal> getAllSortedPriceAscending();

    List<Animal> getAllSortedPriceDescending();

    Set<String> getAnimalsTypes();
}
