package com.tur.controllers;

import com.tur.domain.Animal;
import com.tur.services.AnimalService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;


@Controller
@RequestMapping("/rest")
public class HomeController {

    @Autowired
    AnimalService animalService;
                                                                    //Start of **REST API**
    @RequestMapping(method = RequestMethod.POST)
    public @ResponseBody Long create(@RequestBody Animal animal) {
        return animalService.create(animal);                        //Return autogenerated animalId
    }

    @RequestMapping(value = "/{animalId}", method = RequestMethod.GET)
    public @ResponseBody Animal read(@PathVariable String animalId) {
        return animalService.read(Long.parseLong(animalId));
    }

    @RequestMapping(value = "/{animalId}", method = RequestMethod.PUT)
    public @ResponseBody void update(@RequestBody Animal animal, @PathVariable String animalId) {
        animalService.update(Long.parseLong(animalId), animal);
    }

    @RequestMapping(value = "/{animalId}", method = RequestMethod.DELETE)
    public @ResponseBody void delete(@PathVariable Long animalId) {
        animalService.delete(animalId);
    }
                                                                    //End of **Rest API**

    @RequestMapping("/welcome")
    public String welcome(Model model) {
        model.addAttribute("greeting", "Welcome to Web Store!");
        model.addAttribute("tagline", "The one and only amazing webstore");

        Animal animal = animalService.read(13L);
        animal.setType("Pies");
        animal.setSize("Big");
        animal.setCountry("Polska");
        animal.setUnitPrice(1000);

        animalService.update(13L, animal);
        //animalService.delete(12L);
        return "welcome";
    }
}