package com.tur.controllers;

import com.tur.domain.Animal;
import com.tur.services.AnimalService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;


@Controller
@RequestMapping("/rest")
public class RestController {

    @Autowired
    AnimalService animalService;
                                                                    //Start of **REST API**
    @RequestMapping(method = RequestMethod.POST)
    public @ResponseBody Long create(@RequestBody Animal animal) {
        return animalService.create(animal);                        //Return autogenerated animalId
    }

    @RequestMapping(value = "/{animalId}", method = RequestMethod.GET)
    public @ResponseBody Animal read(@PathVariable String animalId) {
        return animalService.read(Long.parseLong(animalId));
    }

    @RequestMapping(value = "/{animalId}", method = RequestMethod.PUT)
    public @ResponseBody void update(@RequestBody Animal animal, @PathVariable String animalId) {
        animalService.update(Long.parseLong(animalId), animal);
    }

    @RequestMapping(value = "/{animalId}", method = RequestMethod.DELETE)
    public @ResponseBody void delete(@PathVariable Long animalId) {
        animalService.delete(animalId);
    }
                                                                    //End of **Rest API**


}