package com.tur.controllers;

import com.tur.domain.Animal;
import com.tur.services.AnimalService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Set;


@Controller
@RequestMapping("/rest")
public class RestController {

    @Autowired
    AnimalService animalService;
                                                                    //Start of **REST API**
    @RequestMapping(method = RequestMethod.POST)
    public @ResponseBody Long create(@RequestBody Animal animal) {
        return animalService.create(animal);                        //Return autogenerated animalId
    }

    @RequestMapping(value = "/{animalId}", method = RequestMethod.GET)
    public @ResponseBody Animal read(@PathVariable String animalId) {
        return animalService.read(Long.parseLong(animalId));
    }

    @RequestMapping(value = "/{animalId}", method = RequestMethod.PUT)
    public @ResponseBody void update(@RequestBody Animal animal, @PathVariable String animalId) {
        animalService.update(Long.parseLong(animalId), animal);
    }

    @RequestMapping(value = "/{animalId}", method = RequestMethod.DELETE)
    public @ResponseBody void delete(@PathVariable Long animalId) {
        animalService.delete(animalId);
    }
                                                                    //End of **Rest API**

    @RequestMapping(value = "/all", method = RequestMethod.GET)
    public @ResponseBody List<Animal> getAll() {
        return animalService.getAll();
    }

    @RequestMapping(value = "/sA", method = RequestMethod.GET)
    public @ResponseBody List<Animal> getAllSortedAlphabetically() {
        return animalService.getAllSortedAlphabetically();
    }

    @RequestMapping(value = "/sRA", method = RequestMethod.GET)
    public @ResponseBody List<Animal> getAllSortedReverseAlphabetically() {
        return animalService.getAllSortedReverseAlphabetically();
    }

    @RequestMapping(value = "/sPA", method = RequestMethod.GET)
    public @ResponseBody List<Animal> getAllSortedPriceAscending() {
        return animalService.getAllSortedPriceAscending();
    }

    @RequestMapping(value = "/sPD", method = RequestMethod.GET)
    public @ResponseBody List<Animal> getAllSortedPriceDescending() {
        return animalService.getAllSortedPriceDescending();
    }

    @RequestMapping(value = "/aTypes", method = RequestMethod.GET)
    public @ResponseBody Set<String> getAnimalsTypes() {
        return animalService.getAnimalsTypes();
    }
}